version: '3.8'

services:
  xwallet-api-dev:
    build:
      context: docker
      dockerfile: Dockerfile
      target: builder  # 개발용으로 builder 스테이지만 사용
    container_name: xwallet-api-dev
    restart: unless-stopped
    ports:
      - "3030:3030"
    environment:
      - HOST=0.0.0.0
      - PORT=3030
      - LOG_LEVEL=debug
      - RUST_LOG=xWallet=debug,warp=debug
    volumes:
      # 소스 코드 마운트 (핫 리로드용)
      - .:/app/xwallet
      - cargo_cache:/usr/local/cargo/registry
    networks:
      - xwallet-network
    command: cargo run

volumes:
  cargo_cache:

networks:
  xwallet-network:
    driver: bridge
